"""
Export conference_benchmarks from the SIR database to a JavaScript file.

This replaces the hardcoded CONF_DATA object in the website with real data.
Run after build_benchmarks.py to keep the website in sync.

Usage:
    python analytics/export_js.py --season 2025-26 --out ../sir-website/benchmarks.js

The generated file exports a single `CONF_DATA` constant that the website
imports exactly as before — no other JS changes needed.
"""

import sqlite3
import json
import argparse
from pathlib import Path
from datetime import datetime

ROOT    = Path(__file__).parent.parent
DB_PATH = ROOT / "database" / "swim_impact.db"
OUT_DEFAULT = ROOT.parent / "sir-website" / "benchmarks.js"


def export_benchmarks_js(season: str, out_path: Path = None,
                          db_path: Path = None) -> Path:
    out  = out_path or OUT_DEFAULT
    conn = sqlite3.connect(db_path or DB_PATH)
    conn.row_factory = sqlite3.Row
    cur  = conn.cursor()

    cur.execute("""
        SELECT conference, division, gender, event,
               n, p10, p25, p50, p75, p90, p_min as size
        FROM conference_benchmarks
        WHERE season=?
        ORDER BY gender, conference, event
    """, (season,))
    rows = cur.fetchall()
    conn.close()

    if not rows:
        print(f"No benchmark data found for season {season}")
        return None

    # Structure: data[gender][event][conference] = {p10,p25,...,size}
    data: dict = {"M": {}, "F": {}}
    for r in rows:
        g    = r["gender"]
        ev   = r["event"]
        conf = r["conference"]
        if g not in data:
            continue
        if ev not in data[g]:
            data[g][ev] = {}
        # Use n (actual count) as size for rank calculations
        data[g][ev][conf] = {
            "p10":  round(r["p10"],  3),
            "p25":  round(r["p25"],  3),
            "p50":  round(r["p50"],  3),
            "p75":  round(r["p75"],  3),
            "p90":  round(r["p90"],  3),
            "size": r["n"],
        }

    # Normalise event keys to JS-friendly format (e.g. "100 Free" → "100free")
    def ev_key(name: str) -> str:
        return name.lower().replace(" ", "")

    data_keyed: dict = {"M": {}, "F": {}}
    for g in ("M", "F"):
        for ev, confs in data[g].items():
            data_keyed[g][ev_key(ev)] = confs

    # Generate JS
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    js = f"""// AUTO-GENERATED by export_js.py — {generated}
// Season: {season}
// Do not edit by hand. Re-run: python analytics/export_js.py --season {season}

const CONF_DATA = {json.dumps(data_keyed, indent=2)};

// Also export raw event list for dynamic UI dropdowns
const EVENTS_AVAILABLE = {json.dumps(sorted(set(ev_key(e) for g in data for e in data[g])), indent=2)};

// Export season metadata
const SIR_SEASON = "{season}";
const SIR_GENERATED = "{generated}";
"""

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(js)
    print(f"✓ Exported {len(rows)} benchmarks → {out}")

    # Print summary table
    print(f"\n  {'Conference':<18} {'Gender':<6} {'Events':<6} {'Swimmers (avg)'}")
    print(f"  {'─'*18} {'─'*6} {'─'*6} {'─'*14}")
    conf_summary: dict = {}
    for r in rows:
        key = (r["conference"], r["gender"])
        if key not in conf_summary:
            conf_summary[key] = {"events": 0, "n_sum": 0}
        conf_summary[key]["events"] += 1
        conf_summary[key]["n_sum"]  += r["n"]
    for (conf, g), v in sorted(conf_summary.items()):
        avg_n = v["n_sum"] // v["events"]
        print(f"  {conf:<18} {g:<6} {v['events']:<6} ~{avg_n}")

    return out


def main():
    ap = argparse.ArgumentParser(description="Export SIR benchmarks to JavaScript")
    ap.add_argument("--season", "-s", required=True, help="e.g. 2025-26")
    ap.add_argument("--out",    "-o", default=None,
                    help=f"Output JS file (default: {OUT_DEFAULT})")
    ap.add_argument("--db", default=None)
    args = ap.parse_args()

    out = Path(args.out) if args.out else None
    db  = Path(args.db)  if args.db  else None
    export_benchmarks_js(args.season, out, db)


if __name__ == "__main__":
    main()
